# Some defaults in cases where command line args are not given.
default <- list(
  mnt_dir = "/Users/moorer/projects/stec_cattle_microbiome_16s",
  num_threads = 4
)

# A bunch of constants
const <- list(
  dir = list(),
  file = list(),
  primer = list(
    forward_5p_adapter         = "ACTCCTACGGGAGGCAGCAG",
    forward_5p_adapter_revcomp = "CTGCTGCCTCCCGTAGGAGT",
    reverse_3p_adapter         = "GGACTACHVGGGTWTCTAAT",
    reverse_3p_adapter_revcomp = "ATTAGAWACCCBDGTAGTCC"
  ),
  env = list(
    user = system("id -un $(whoami)", intern = TRUE),
    group = system("id -gn $(whoami)", intern = TRUE)
  ),
  param = list(
    num_threads = if (exists("arg_num_threads")) {
      arg_num_threads
    } else if (!is.null(params$num_threads)) {
      params$num_threads
    } else {
      default$num_threads
    }
  )
)

## Directories

# This is the mounted volume.  Grabs this from the environment when `run_analysis.R` is called.
const$dir$mnt <- if (exists("arg_mnt_dir")) {
  arg_mnt_dir
} else if (!is.null(params$mnt_dir)) {
  params$mnt_dir
} else {
  default$mnt_dir
}

# Reads will be copied out of this directory.  Nothing in here will be changed.
const$dir$orig_reads <- file.path(const$dir$mnt, "original_reads")

# To speed up I/O bound programs, we need to do all work in a file that is not mapped to a mounted volume.
const$dir$work <- "/home/work"

# At the end of the pipeline, all output will be moved here.  You can access this from the host.
const$dir$pipeline_output <- file.path(const$dir$mnt, "pipeline_output")

## Files

# Reads from all samples with vsearch sample identifiers
const$file$all_reads <- file.path(const$dir$work, "all_reads.fa")

# Lengths for all_reads
const$file$read_lengths <- file.path(const$dir$work, "all_reads.lengths.txt")

# A small subset of all_reads
const$file$read_subset <- file.path(const$dir$work, "all_reads.subset.fa")

# Generated by `vsearch --derep_fulllength`
const$file$derep_seqs <- file.path(const$dir$work, "derep_seqs.fa")

# Generated by `vsearch --cluster_unoise`
const$file$unoise_seqs <- file.path(const$dir$work, "unoise_seqs.fa")

# Chimera free unoise seqs
const$file$asv_seqs <- file.path(const$dir$work, "asv_seqs.fa")

# Count table from searching all reads against ASVs
const$file$asv_count_table <- file.path(const$dir$work, "asv_seqs.count_table.txt")
